# permissions for end users to view backandfronts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backandfront-viewer-role
rules:
- apiGroups:
  - devops.gxin0426
  resources:
  - backandfronts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devops.gxin0426
  resources:
  - backandfronts/status
  verbs:
  - get
